### ISSUE TITLE
is it done? not complete app?

### ISSUE THREAD

**Issue by Saruultugs** [pranjalkumar/Badge#1]
is it done? not complete app?
I tried to use your app. not working.

baadg.herokuapp.com

**Comment by pranjalkumar** [comment]
Its done..
But i have deleted the app from fb dashboard.
U can use it by changing the app id in index.php (replacing by our own app id)

**Comment by pranjalkumar** [comment]
also replace the external photo url by your own url
and make sure that your app has the publish action permission via facebook.

**Comment by pranjalkumar** [comment]
If you are behind the proxy make sure to add that as i have done in my youtube downloader

**Comment by pranjalkumar** [comment]
Yep its done
